### PR TITLE
Revision of API Documentation: SOAP Part 4

### PR DESCRIPTION
**Pull request by tmewes**
# Description

This PR revises a bunch of the SOAP API Documentation as a fourth part of the complete overhaul and
- adjusts the `Maho` branding.
- fixes some small typos.
- simplifies and standardizes the wording of some terms.
- replaces all `http` links with `https`.
- introduces the array short form in the code examples.
- reformats the file.

The changes in this PR are just suggestions as usual. If you like the changes, I will create the next PRs step by step. :)

# Type of change

- Refactor

### CODE REVIEW

**Comment by fballiano** [comment]
auch, the thing that I didn't notice in the previous PRs is this, you changed some bold text to ### but this creates a lot of elements in the "table of contents" sidebar, which to me are making the TOC itself a bit confusing and that was why I left them just as bold text:

Screenshot 2024-09-13 alle 09 32 54

what do you think?

**Comment by tmewes** [comment]
Oh, I'm sorry, I thought that was already clear in the previous PRs.

I tried to create a clear and recurring structure for these pages. In my opinion, if you just use bold text, this structure is... I would say at least improvable/optimizable, also for SEO reasons. That's why I have added more subheadings here.

I can of course change everything again if you want, but in my opinion the current TOC display is more of a problem in this case than the content on the respective main page.

Maybe we should set a maximum depth of TOC:
https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.toc_depth

Alternatively, we could change the `###` and `####` in the API Markdown documents to `<h3>` and `<h4>` (and leave everything else as it is). Then the main content HTML source code would remain the same, but these subheadings would not appear in the TOC. I have just tested this successfully. Perhaps this would also be a good solution.

Which solution would you like?
1. Leave it as it is now with the huge TOC.
2. Set a maximum depth of the TOC.
3. Switch from  `###` and `####` to `<h3>` and `<h4>` at least in the API docs.

**Comment by fballiano** [comment]
I missed it :-(

I teste the TOC depth but I think we shouldn't limit it because it other pages of the website it may be used, and it should be limited to "2" levels which is too little.

I didn't know that having `<h3>` would avoid the element to be included in the TOC, this to be seems a good solution.

IMHO either `<h3>` or setting them back to a simple bold (that can be done with a regex replace in the IDE) are good solutions :-)

**Comment by tmewes** [comment]
Okay, then `<h3>` and `<h4>` it is. :) All files up to this point have been updated now. Could you please give it a try?

**Comment by fballiano** [comment]
I think docs/api/soap.md shouldn't be changed, the rest seems of from a first look

**Comment by tmewes** [comment]
> I think docs/api/soap.md shouldn't be changed

May I ask why? I've thought about it too, but haven't found a reason for this inconsistency.
I have no problem restoring it, but I'd be interested to hear your reasoning. :)

**Comment by fballiano** [comment]
simply because the TOC of that page is not like a reference to a SOAP method and it seems more clear to me as it was before, highlighing the important things ;-)

**Comment by tmewes** [comment]
Okay, thanks! Here we go. :)

**Pull request merged**
